[package]
name = "rustorrent"
version = "0.1.0"
authors = ["optifat <pavsmel@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.4"
curl = "0.4.36"
rand = "0.8.3"
